/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.4 at Fri Jan 10 13:32:02 2020. */

#include "abckey_messages_mnemonic.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t reqmnemonic_fields[2] = {
    PB_FIELD(  1, BYTES   , REQUIRED, CALLBACK, FIRST, reqmnemonic, req, req, 0),
    PB_LAST_FIELD
};

const pb_field_t rsp_mnemonic_fields[2] = {
    PB_FIELD(  1, BYTES   , REQUIRED, CALLBACK, FIRST, rsp_mnemonic, mnemonic, mnemonic, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
