/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.4 at Fri Jan 10 11:55:08 2020. */

#include "abckey_messages_pubkey.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t TxPublicKeyMod_fields[2] = {
    PB_FIELD(  1, BYTES   , REQUIRED, CALLBACK, FIRST, TxPublicKeyMod, PublicKey_Mod, PublicKey_Mod, 0),
    PB_LAST_FIELD
};

const pb_field_t TxPublicKeyModSign_fields[2] = {
    PB_FIELD(  1, BYTES   , REQUIRED, CALLBACK, FIRST, TxPublicKeyModSign, PublicKey_Mod_Sign, PublicKey_Mod_Sign, 0),
    PB_LAST_FIELD
};

const pb_field_t RspTxPublicKeyMod_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, RspTxPublicKeyMod, Rsp, Rsp, 0),
    PB_LAST_FIELD
};

const pb_field_t RspTxPublicKeyModSign_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, RspTxPublicKeyModSign, Res, Res, 0),
    PB_LAST_FIELD
};

const pb_field_t TxPublicKeyExp_fields[2] = {
    PB_FIELD(  1, BYTES   , REQUIRED, CALLBACK, FIRST, TxPublicKeyExp, PublicKey_Exp, PublicKey_Exp, 0),
    PB_LAST_FIELD
};

const pb_field_t TxPublicKeyExpSign_fields[2] = {
    PB_FIELD(  1, BYTES   , REQUIRED, CALLBACK, FIRST, TxPublicKeyExpSign, PublicKey_Exp, PublicKey_Exp, 0),
    PB_LAST_FIELD
};

const pb_field_t RspTxPublicKeyExp_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, RspTxPublicKeyExp, Rsp, Rsp, 0),
    PB_LAST_FIELD
};

const pb_field_t RspTxPublicKeyExpSign_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, RspTxPublicKeyExpSign, Rsp, Rsp, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
