/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.4 at Fri Jan 10 11:55:08 2020. */

#ifndef PB_ABCKEY_MESSAGES_PUBKEY_PB_H_INCLUDED
#define PB_ABCKEY_MESSAGES_PUBKEY_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _RspTxPublicKeyExp {
    pb_callback_t Rsp;
/* @@protoc_insertion_point(struct:RspTxPublicKeyExp) */
} RspTxPublicKeyExp;

typedef struct _RspTxPublicKeyExpSign {
    pb_callback_t Rsp;
/* @@protoc_insertion_point(struct:RspTxPublicKeyExpSign) */
} RspTxPublicKeyExpSign;

typedef struct _RspTxPublicKeyMod {
    pb_callback_t Rsp;
/* @@protoc_insertion_point(struct:RspTxPublicKeyMod) */
} RspTxPublicKeyMod;

typedef struct _RspTxPublicKeyModSign {
    pb_callback_t Res;
/* @@protoc_insertion_point(struct:RspTxPublicKeyModSign) */
} RspTxPublicKeyModSign;

typedef struct _TxPublicKeyExp {
    pb_callback_t PublicKey_Exp;
/* @@protoc_insertion_point(struct:TxPublicKeyExp) */
} TxPublicKeyExp;

typedef struct _TxPublicKeyExpSign {
    pb_callback_t PublicKey_Exp;
/* @@protoc_insertion_point(struct:TxPublicKeyExpSign) */
} TxPublicKeyExpSign;

typedef struct _TxPublicKeyMod {
    pb_callback_t PublicKey_Mod;
/* @@protoc_insertion_point(struct:TxPublicKeyMod) */
} TxPublicKeyMod;

typedef struct _TxPublicKeyModSign {
    pb_callback_t PublicKey_Mod_Sign;
/* @@protoc_insertion_point(struct:TxPublicKeyModSign) */
} TxPublicKeyModSign;

/* Default values for struct fields */

/* Initializer values for message structs */
#define TxPublicKeyMod_init_default              {{{NULL}, NULL}}
#define TxPublicKeyModSign_init_default          {{{NULL}, NULL}}
#define RspTxPublicKeyMod_init_default           {{{NULL}, NULL}}
#define RspTxPublicKeyModSign_init_default       {{{NULL}, NULL}}
#define TxPublicKeyExp_init_default              {{{NULL}, NULL}}
#define TxPublicKeyExpSign_init_default          {{{NULL}, NULL}}
#define RspTxPublicKeyExp_init_default           {{{NULL}, NULL}}
#define RspTxPublicKeyExpSign_init_default       {{{NULL}, NULL}}
#define TxPublicKeyMod_init_zero                 {{{NULL}, NULL}}
#define TxPublicKeyModSign_init_zero             {{{NULL}, NULL}}
#define RspTxPublicKeyMod_init_zero              {{{NULL}, NULL}}
#define RspTxPublicKeyModSign_init_zero          {{{NULL}, NULL}}
#define TxPublicKeyExp_init_zero                 {{{NULL}, NULL}}
#define TxPublicKeyExpSign_init_zero             {{{NULL}, NULL}}
#define RspTxPublicKeyExp_init_zero              {{{NULL}, NULL}}
#define RspTxPublicKeyExpSign_init_zero          {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define RspTxPublicKeyExp_Rsp_tag                1
#define RspTxPublicKeyExpSign_Rsp_tag            1
#define RspTxPublicKeyMod_Rsp_tag                1
#define RspTxPublicKeyModSign_Res_tag            1
#define TxPublicKeyExp_PublicKey_Exp_tag         1
#define TxPublicKeyExpSign_PublicKey_Exp_tag     1
#define TxPublicKeyMod_PublicKey_Mod_tag         1
#define TxPublicKeyModSign_PublicKey_Mod_Sign_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t TxPublicKeyMod_fields[2];
extern const pb_field_t TxPublicKeyModSign_fields[2];
extern const pb_field_t RspTxPublicKeyMod_fields[2];
extern const pb_field_t RspTxPublicKeyModSign_fields[2];
extern const pb_field_t TxPublicKeyExp_fields[2];
extern const pb_field_t TxPublicKeyExpSign_fields[2];
extern const pb_field_t RspTxPublicKeyExp_fields[2];
extern const pb_field_t RspTxPublicKeyExpSign_fields[2];

/* Maximum encoded size of messages (where known) */
/* TxPublicKeyMod_size depends on runtime parameters */
/* TxPublicKeyModSign_size depends on runtime parameters */
/* RspTxPublicKeyMod_size depends on runtime parameters */
/* RspTxPublicKeyModSign_size depends on runtime parameters */
/* TxPublicKeyExp_size depends on runtime parameters */
/* TxPublicKeyExpSign_size depends on runtime parameters */
/* RspTxPublicKeyExp_size depends on runtime parameters */
/* RspTxPublicKeyExpSign_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ABCKEY_MESSAGES_PUBKEY_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
